"""goods model fix

Revision ID: 8f7793822241
Revises: a34f17e89843
Create Date: 2023-11-10 11:53:46.027770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7793822241'
down_revision: Union[str, None] = 'a34f17e89843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Goods', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Goods', type_='unique')
    # ### end Alembic commands ###
