"""new purchases entries model

Revision ID: a34f17e89843
Revises: d59e78389f6e
Create Date: 2023-11-10 10:17:53.765726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34f17e89843'
down_revision: Union[str, None] = 'd59e78389f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PurchaseEntries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('summary_price', sa.Float(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Goods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['Purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PurchaseEntries')
    # ### end Alembic commands ###
