version: "3.8"
services:
  shop-api:
    container_name: shop-api
    build: ./api
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 5000"
    depends_on:
      - shop-db
    restart: on-failure
    ports:
      - "8181:5000"
  shop-db:
    image: postgres
    environment:
      POSTGRES_DB: "shopdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "testpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

volumes:
  shopdb-data: